### PR TITLE
Update and Extension of WOF Algorithm. Added LCSA and GLMO Method for…

### PR DESCRIPTION
**Pull request by hz2014hz**
This provides and update and extensions to the large-scale Weighted Optimization Framework (WOF) and futher adds two new algorithms (GLMO and LCSA) for large-scale multi-objective optimization. 
- WOF now works with 4 different suboptimisers (NSGA-II, NSGA-III, MOEAD, SMPSO) and a randomised mode which achieves better performance. The update and extensions are based on the recent study in [1]. 
- LCSA is a recent method using linear combinations of existing solutions to tackle large-scale multi-objective optimization. It is described in detail in [1] and [2]. 
- GLMO uses variable groups inside existing mutation operators and has been shown work well for large-scale problems. It is based on [1] and [3]. 

[1] Heiner Zille, "Large-scale Multi-objective Optimisation: New Approaches and a Classification of the State-of-the-Art", PhD Thesis, Otto von Guericke University Magdeburg, 2019, http://dx.doi.org/10.25673/32063 

[2] Heiner Zille and Sanaz Mostaghim, "Linear Search Mechanism for Multi- and Many-Objective Optimisation", 10th International Conference on Evolutionary Multi-Criterion Optimization (EMO 2019), Lecture Notes in Computer Science, vol 11411. Deb K. et al. (eds), Springer, Cham, East Lansing, Michigan, USA, March 2019, https://doi.org/10.1007/978-3-030-12598-1_32.

[3] Heiner Zille, Hisao Ishibuchi, Sanaz Mostaghim and Yusuke Nojima, "Mutation Operators Based on Variable Grouping for Multi-objective Large-scale Optimization", IEEE Symposium Series on Computational Intelligence (SSCI), IEEE, Athens, Greece, December 2016, https://ieeexplore.ieee.org/document/7850214

### CODE REVIEW

**Comment by anonymone** [comment]
@hz2014hz This PR has already merged into the master branch. Thanks for your contribution! To keep code in the same format, we upload our version.

**Comment by hz2014hz** [comment]
@anonymone Thanks for including the GLMO and LCSA. 
However, you seem to not have included the updated WOF algorithm in your update. As I wrote, this new version from my PR contains new functionality and increased performance based on the current publications, so it would be nice to share this with the community as well. It can replace the current WOFSMPSO folder since it contains multiple subalgorithms and not just SMPSO. 
Could you consider uploading the WOF Code from the PR too? 
Thanks!
Heiner Zille

**Comment by anonymone** [comment]
@hz2014hz Hi, the update of WOF has done! #58  Thank you for reminding me.

**Comment by hz2014hz** [comment]
@anonymone Awesome, thank you!

**Pull request closed without merging**
